### ISSUE TITLE
Art Unit classification rather than patent classification

### ISSUE THREAD

**Issue by dah366** [FirstToDisclose/CodeAcrossBoston#21]
Might want to focus on using art unit for tags right now since they are broader

List of art units and corresponding numbers: http://www.uspto.gov/sites/default/files/documents/caau_1.pdf

**Comment by jwalsh** [comment]
Background: patent classification might not be the right fit (the patent classification system may be way way too largescale and instead this "art unit" would be much better because it is smaller and used by inventors as opposed to patent examiners).  The idea is to use Q&A markup as the way to elicit the right classification codes from users submitting disclosures.  This will result in a tag list.

**Comment by dazzaji** [comment]
Here is a great Wikipedia overview info re Patent Classification systems (describing how patent classes are assigned to Art Codes): https://github.com/FirstToDisclose/CodeAcrossBoston/blob/master/docs/UnitedStatesPatentClassification.pdf?raw=true
From: http://en.wikipedia.org/wiki/United_States_Patent_Classification

**Comment by jwalsh** [comment]
This issue was moved to FirstToDisclose/firsttodisclose.net#12
